research_task:
  description: >
    Investigate financial results for the company {company} for the current year {current_year} and last year,
    and write a report with summarized financial information. Go step by step and Summarize each web page 
    you find before read the next. Include company activity and history details in the report.
  expected_output: >
    A detailed report of the financial information for the company {company} from the last and current year
    {current_year}.

analysis_task:
  description: >
    Get the report from research task for the company {company} and make a summarized financial analysis to 
    determine if it is worth to invest. Make an introduction about the company activity and history. Don't worry
    if you don't have all the financial information for the current year as it is not finished yet, but include
    all the information you have. As final information always say that the report is only a recommendation, final
    decision to invest depends on the customer.
  expected_output: >
    A summarized report with financial results analysis for the company and advice to invest in or not. Never 
    show the errors you received from the tools. If you don't have information about last year, just output 
    you don't have enough information to make any advice.
    Must be markdown format.

write_email_task:
  description: >
    Write a formal and professional e-mail to your customer persuading him/her to invest in the company 
    from the generated report by the financial results ananlyst and explaining why it is worth to invest.
    If you want to make references to the generated report, say that it is a report generated by our best analysts.
    Show report detailed information.
    Must be markdown format.
  expected_output: >
    A professional and formal e-mail
